### ISSUE TITLE
Sentence Structure in Paragraph Two

### ISSUE THREAD

**Issue by Mitchello457** [comptonb37/about-me#1]
Within your latest edit, e1624409e1061b5e073cb9cfc7f5ed7ac38b9ea3, take a look at the sentence that begins "Brian also took many AP courses in English". Instead of using to phrasing "but can say he learned" use only the word "learned" or change the structure completely. One way that this might be done is that instead of using "but can say he learned", use "yet learned the most from". You may want to cut out the "about writing within that sentence because it is redundant with the next sentence. Also in this sentence, you say "him" instead of "his" before stating that the class was AP English Language.

**Comment by comptonb37** [comment]
These changes have been made and the case will be closed. Thank you for the feedback
