### ISSUE TITLE
Addition to Final Sentence of First Paragraph

### ISSUE THREAD

**Issue by Mitchello457** [comptonb37/about-me#2]
In the latest version, e1624409e1061b5e073cb9cfc7f5ed7ac38b9ea3, you might want to mention some of the video games that you played on the computer because it would allow the ready to relate to you and become connected. Maybe they played the same games as you or see a game that they might be interested in because of the connection in interests. Just add to the end of the sentence the phrase "such as" and then list the two or three games that were your favorite to play.

**Comment by comptonb37** [comment]
I decided to make a whole new paragraph on that and the friends it has helped me gain, so thanks for the input. This case will be closed because of this
